[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cd packages/shared && npm run build",
  "cd apps/server && npm run build"
]

[start]
cmd = "cd apps/server && npm run start"

[variables]
NODE_ENV = "production"
